# Generated by Django 3.2.5 on 2021-07-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
    ]
