# Generated by Django 3.2.5 on 2021-07-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_giftvoucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftvoucher',
            name='amount',
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='name',
            field=models.CharField(default='Gift Voucher', max_length=254),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='select_amount',
            field=models.IntegerField(choices=[(50.0, '€50.00'), (100.0, '€100.00'), (150.0, '€150.00'), (200.0, '€200.00'), (250.0, '€250.00'), (300.0, '€300.00'), (350.0, '€350.00'), (400.0, '€400.00')], default=0),
        ),
    ]
