# Generated by Django 3.2.5 on 2021-07-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210713_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftVoucher',
        ),
    ]
